name: cs344
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  overlay_loading_progress: ^1.0.0
  http: ^0.13.5
  shared_preferences: ^2.0.15
  cupertino_icons: ^1.0.2
  timelines: ^0.1.0
  flutter:
    sdk: flutter
  call_log: ^4.0.0
  flutter_isolate: ^2.0.2
  permission_handler: ^10.0.0
  workmanager: ^0.5.0
  flutter_background: ^1.1.0
  flutter_foreground_task: ^3.9.0
  phone_state: ^1.0.2
  system_alert_window: ^1.1.2
  awesome_notifications: ^0.6.21
  
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  fonts:
    - family: Helvetica
      fonts:
        - asset: assets/Helvetica.ttf
        - asset: assets/Helvetica-Oblique.ttf
          style: italic

  assets:
    - assets/scaffold.png
    - assets/logo.png

  uses-material-design: true


